name: Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Tidy
      working-directory: ./server
      run:
      - go mod tidy -x
      - git diff --exit-code go.mod go.sum

    - name: Test
      working-directory: ./server
      run: go test -v ./...

